from dataclasses import dataclass

from polynet.options.enums import ProblemTypes, StringRepresentation

"""In this file, we define the PlottingOptions dataclass, which is used to store the plotting
preferences, defined in the UI for the plots generated by the Helix package. All plots
will then have the same style, such as font size, font family, colour scheme, etc."""


@dataclass
class DataOptions:
    data_name: str
    data_path: str
    smiles_cols: list[str]
    canonicalise_smiles: bool
    string_representation: StringRepresentation = StringRepresentation.Smiles
    id_col: str | None = None
    target_variable_col: str
    problem_type: ProblemTypes
    num_classes: int | None = None
    target_variable_name: str | None = None
    class_names: dict[str, str] | None = None
    target_variable_units: str | None = None

    # graph_feats: dict[str, list[str]]
    # one_hot_encode_feats: list[str]
    # ratio_col: str
    # include_graph_feats: bool
