from dataclasses import dataclass
from polynet.options.enums import MolecularDescriptors

"""In this file, we define the PlottingOptions dataclass, which is used to store the plotting
preferences, defined in the UI for the plots generated by the Helix package. All plots
will then have the same style, such as font size, font family, colour scheme, etc."""


# TODO: remove the rdkit_descriptors, df_descriptors, and polybert_fp and just keep the molecular_descriptors dict
@dataclass
class RepresentationOptions:
    molecular_descriptors: dict[MolecularDescriptors, list[str]]
    rdkit_descriptors: list[str]
    df_descriptors: list[str]
    rdkit_independent: bool
    df_descriptors_independent: bool
    mix_rdkit_df_descriptors: bool
    smiles_merge_approach: list
    node_feats: dict
    edge_feats: dict
    weights_col: dict[str, str] | None
    polybert_fp: bool = False
